name: Node js project build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build the project
      run: | 
            npm ci
            npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
          name: build-file
          path: build
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout repo
      use: actions/checkout@v2
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: build-file
        path: ./build
    

    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
          branch: gh-pages 
          folder: build